server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  title: ${spring.application.name}
  version: ${spring.application.version}
  description: api接口文档
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    show-actuator: false
  api-docs:
    path: /api-docs