server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  mvc:
    pathmatch:
      # see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#pathpattern-based-path-matching-strategy-for-spring-mvc
      matching-strategy: ANT_PATH_MATCHER